site_name: Simtestlab Documentation
site_description: Documentation for Simtestlab project
site_author: Simtestlab
site_url: https://simtestlab.github.io/simtestlab/

# Repository
repo_name: Simtestlab/simtestlab
repo_url: https://github.com/Simtestlab/simtestlab

# Theme
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Navigation
nav:
  - Home: index.md
  - Diagrams: diagrams.md

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
